spring:
  application:
    name: user-service
  config:
    import: classpath:application-database.yml
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  shutdown: graceful  # 애플리케이션 종료 시 정상 종료 (Graceful Shutdown)
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://yunjae.click:19090/eureka/

jwt:
  secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1
