version: '3.7'
services:
  redis:
    container_name: radiata-dev-redis-total
    image: redis:7.2-alpine
    command: redis-server --port 6380
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6380:6380
  mysql:
    container_name: radiata-dev-postgres-total
    image: postgres:latest
    command: postgres -c 'max_connections=200' # 기본 설정은 100 이나, 동시 연결 수 제한을 200 까지 풀기 위함
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=radiata-dev-postgres-total
      - POSTGRES_USER=radiata
      - POSTGRES_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d