services:
  payment-server:
    image: wodbs7758/autumn-payment-server:latest
    container_name: autumn-payment-server
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=service/payment/payment-api
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  order-server:
    image: wodbs7758/autumn-order-server:latest
    container_name: autumn-order-server
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=service/order/order-api
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server

  brand-server:
    image: wodbs7758/autumn-brand-server:latest
    container_name: autumn-brand-server
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=service/brand/brand-api
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server

  coupon-server:
    image: wodbs7758/autumn-coupon-server:latest
    container_name: autumn-coupon-server
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=service/coupon/coupon-api
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  timesale-server:
    image: wodbs7758/autumn-timesale-server:latest
    container_name: autumn-timesale-server
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=service/timesale/timesale-api
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  user-server:
    image: wodbs7758/autumn-user-server:latest
    container_name: autumn-user-server
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=service/user/user-api
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server

  gateway-server:
    image: wodbs7758/autumn-gateway-server:latest
    container_name: autumn-gateway-server
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=service/gateway/gateway-core
    ports:
      - "19091:19091"
    depends_on:
      - eureka-server

  eureka-server:
    image: wodbs7758/autumn-eureka-server:latest
    container_name: autumn-eureka-server
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=service/eureka/eureka-core
    ports:
      - "19090:19090"

volumes:
  postgres_main_volume:
  postgres_batch_volume:
  redis_volume:

