spring:
  config:
    import: classpath:application-database.yml
  application:
    name: coupon-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://yunjae.click:19090/eureka/
