server:
  port: 19091
  shutdown: graceful  # 애플리케이션 종료 시 정상 종료 (Graceful Shutdown)
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      filter:
        circuit-breaker:
          enabled:
  lifecycle:
    timeout-per-shutdown-phase: 12s

eureka:
  client:
    service-url:
      defaultZone: http://yunjae.click:19090/eureka/

jwt:
  secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - url: http://yunjae.click:8080/v3/api-docs
        name: Payment API
      - url: http://yunjae.click:8081/v3/api-docs
        name: Coupon API
      - url: http://yunjae.click:8082/v3/api-docs
        name: Timesale API
      - url: http://yunjae.click:8083/v3/api-docs
        name: User API
      - url: http://yunjae.click:8484/v3/api-docs
        name: Brand API
      - url: http://yunjae.click:8085/v3/api-docs
        name: Order API

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
