server:
  port: 19091  # ????? ???? ??? ?? ??

spring:
  application:
    name: gateway-service  # ?????? ??? 'gateway-service'? ??
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  cloud:
    gateway:
      filter:
        circuit-breaker:
          enabled:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ??? URL? ??






