server:
  port: 19091  # ????? ???? ??? ?? ??

spring:
  application:
    name: gateway-service  # ?????? ??? 'gateway-service'? ??
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      filter:
        circuit-breaker:
          enabled:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/






