spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/radiata-dev-postgres-total
    username: radiata
    password: 1234
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 63801

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # sql 로깅
        format_sql: true # SQL 문 정렬하여 출력
        highlight_sql: true # SQL 문 색 부여
        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
        dialect: org.hibernate.dialect.PostgreSQLDialect # Hibernate Dialect 추가
