spring:
  application:
    name: brand-service
  config:
    import: classpath:application-database.yml

server:
  port: 8484

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost



