spring:
  application:
    name: brand-service
  config:
    import: classpath:application-database.yml
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  shutdown: graceful  # 애플리케이션 종료 시 정상 종료 (Graceful Shutdown)
  port: 8484

eureka:
  client:
    service-url:
      defaultZone: http://yunjae.click:19090/eureka/
