spring:
  application:
    name: order-service
  config:
    import: classpath:application-database.yml
  profiles:
    default: dev

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost
