spring:
  config:
    import: classpath:application-database.yml
  application:
    name: timesale-consumer-service
  kafka:
    bootstrap-servers: http://yunjae.click:9092


server:
  port: 9082

eureka:
  client:
    service-url:
      defaultZone: http://yunjae.click:19090/eureka/
