spring:
  application:
    name: payment-service
  config:
    import: classpath:application-database.yml # database 속성 가져오기용
  profiles:
    default: dev

eureka:
  client:
    service-url:
      defaultZone: http://yunjae.click:19090/eureka/
  instance:
    hostname: yunjae.click
