spring:
  application:
    name: payment-service
  config:
    import: classpath:application-database.yml # database 속성 가져오기용
  profiles:
    default: dev
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  shutdown: graceful  # 애플리케이션 종료 시 정상 종료 (Graceful Shutdown)

eureka:
  client:
    service-url:
      #      defaultZone: http://yunjae.click:19090/eureka/
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true