spring:
  config:
    import: classpath:application-database.yml
  application:
    name: coupon-consumer-service
  kafka:
    bootstrap-servers: localhost:9092


server:
  port: 9081

eureka:
  client:
    service-url:
      defaultZone: http://yunjae.click:19090/eureka/
