name: CD

on:
  push:
    branches: [ "main" ] # main 브랜치로 merge 시 작동

env:
  AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
  AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_USERNAME }}
  AWS_EC2_SSH_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        service: [ service/eureka/eureka-core, service/gateway/gateway-core, service/user/user-api, service/brand/brand-api, service/order/order-api, service/payment/payment-api, service/coupon/coupon-api, service/timesale/timesale-api ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - run: pwd

      - run: ls -al

      - name: Build with Gradle Wrapper
        #        run: ./gradlew clean build -x test --project-dir ${{ matrix.service }} --warning-mode=all
        run: ./gradlew clean build -x test --warning-mode=all

      # Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      # Docker 이미지 빌드
      - name: Build Docker images
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/autumn-user-server:latest \
            --build-arg FILE_DIRECTORY=service/user/user-api -f ./Dockerfile .
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/autumn-payment-server:latest \
            --build-arg FILE_DIRECTORY=service/payment/payment-api -f ./Dockerfile .
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/autumn-order-server:latest \
            --build-arg FILE_DIRECTORY=service/order/order-api -f ./Dockerfile .
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/autumn-brand-server:latest \
            --build-arg FILE_DIRECTORY=service/brand/brand-api -f ./Dockerfile .
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/autumn-coupon-server:latest \
            --build-arg FILE_DIRECTORY=service/coupon/coupon-api -f ./Dockerfile .
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/autumn-timesale-server:latest \
            --build-arg FILE_DIRECTORY=service/timesale/timesale-api -f ./Dockerfile .
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/autumn-gateway-server:latest \
            --build-arg FILE_DIRECTORY=service/gateway/gateway-core -f ./Dockerfile .
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/autumn-eureka-server:latest \
            --build-arg FILE_DIRECTORY=service/eureka/eureka-core -f ./Dockerfile .

      # Docker Hub에 이미지 푸시
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/autumn-user-server:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/autumn-coupon-server:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/autumn-timesale-server:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/autumn-order-server:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/autumn-brand-server:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/autumn-payment-server:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/autumn-gateway-server:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/autumn-eureka-server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_EC2_HOST }}
          username: ${{ env.AWS_EC2_USERNAME }}
          key: ${{ env.AWS_EC2_SSH_KEY }}
          script: |
            echo ${{ env.DOCKER_HUB_TOKEN }} | docker login -u ${{ env.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose -f ./docker-compose-deploy.yml down
            docker rm -f autumn-user-server
            docker rm -f autumn-coupon-server
            docker rm -f autumn-timesale-server
            docker rm -f autumn-order-server
            docker rm -f autumn-brand-server
            docker rm -f autumn-payment-server
            docker rm -f autumn-gateway-server
            docker rm -f autumn-eureka-server
            docker pull ${{ env.DOCKER_HUB_USERNAME }}/autumn-user-server:latest
            docker pull ${{ env.DOCKER_HUB_USERNAME }}/autumn-coupon-server:latest
            docker pull ${{ env.DOCKER_HUB_USERNAME }}/autumn-timesale-server:latest
            docker pull ${{ env.DOCKER_HUB_USERNAME }}/autumn-order-server:latest
            docker pull ${{ env.DOCKER_HUB_USERNAME }}/autumn-brand-server:latest
            docker pull ${{ env.DOCKER_HUB_USERNAME }}/autumn-payment-server:latest
            docker pull ${{ env.DOCKER_HUB_USERNAME }}/autumn-gateway-server:latest
            docker pull ${{ env.DOCKER_HUB_USERNAME }}/autumn-eureka-server:latest
            docker compose -f ./docker-compose-deploy.yml up -d
